build:
  # The build command for your project
  command: npm run build
  # The directory where your built assets will be placed
  output_directory: out
  # Environment variables required during the build
  environment:
    NODE_VERSION: 22

# Specify the Node.js version
node_version: 22

# Configure build caching
cache:
  # Directories to cache between builds
  directories:
    - node_modules
    - .next/cache

# Configure deployment
deploy:
  # Use the --assets flag to deploy static assets
  command: npx wrangler deploy --assets=./out
